import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  safelist: [
    'bg-sky-500',
    'bg-slate-700',
    'text-sky-400',
    'text-sky-600',
    'text-sky-300',
    'text-slate-300',
    'text-slate-600',
    'text-slate-800',
    'border-sky-500',
    'rounded-full',
    'shadow-md',
    'font-bold',
    'font-semibold',
    'font-medium',
    'text-xs',
    'text-sm',
    'text-lg',
    'w-full',
    'h-2',
    'mb-2',
    'mb-4',
    'mt-1',
    'mt-4',
    'mt-6',
    'gap-2',
    'gap-4',
    'flex',
    'items-center',
    'justify-center',
    'space-y-2',
    'space-y-8',
    'p-4',
    'p-2',
    'rounded',
    'border',
    'border-b',
    'border-4',
    'shadow-xl',
    'bg-white',
    'bg-slate-700',
    'bg-slate-800',
    'bg-slate-900',
    'bg-sky-400',
    'bg-sky-600',
    'bg-sky-300',
    'min-h-screen',
    'text-black',
    'text-white',
    'text-center',
    'w-28',
    'h-28',
    'rounded-full',
    'border-4',
    'border-sky-500',
    'shadow-md',
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          light: "#7E3FFF",
          dark: "#4A11C0",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        gray: {
          light: "#F8F9FA",
          medium: "#E9ECEF",
          dark: "#6C757D",
        },
        text: {
          dark: "#212529",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
